### ISSUE TITLE
[BUG] device_group.py. and load_balancer.py does not properly check if h_mbs is 0 before generating comb_h_mbs

### ISSUE THREAD

**Issue by Jiminator** [SamsungLabs/Metis#7]
### Summary
When using the planner on a heterogenous hostfile, the planner will return a math domain error since the load balancer will assign a bs value of 0 to a device, which is not in the domain of math.log2. Furthermore, the planner also returns a key error as it tries to search for profiling files with h_mbs_slice > MAX_PROFILED_BATCH_SIZE.

### Steps to reproduce

1. Rename profile_data_samples directory to profile
2. Create a clusterfile and hostfile listed in the very bottom of issue description
3. Use the script listed in the bottom to generate synthetic v100 data. the script just copies the a100 profiling data and multiplies the execution time values by 3.5
```
cd ~/Metis
python3 gen_synth_data.py
```
4. run the profiler with the command
```
source ./cost_het_cluster.sh MODEL_NAME=GPT MODEL_SIZE=1.5B NUM_LAYERS=10 GBS=128 HOME_DIR='/home/user' MAX_PROFILED_TP=4 MAX_PROFILED_BATCH_SIZE=4 SCALE_VARIANCE=1 MAX_PERMUTE_LEN=10 
```

### What is the current *bug* behavior?

Errors with a math domain error as the profiler tries to pass in a h_mbs value of 0 into math.log2

### What is the expected *correct* behavior?

No math domain errors and no key errors

### Error Trace
```
Traceback (most recent call last):
  File "/Users/jimmy/Desktop/UIUC/Research/Metis/scripts/../cost_het_cluster.py", line 70, in <module>
    estimate_costs = cost_het_cluster(args, gpu_cluster, profile_data, model_config, cost_estimator, layer_load_balancer)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jimmy/Desktop/UIUC/Research/Metis/scripts/../cost_het_cluster.py", line 37, in cost_het_cluster
    while intra_stage_plan_generator.has_next:
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jimmy/Desktop/UIUC/Research/Metis/search_space/plan.py", line 209, in has_next
    intra_stage_compute_performance = self.stage_performance.get_intra_stage_compute_performance(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jimmy/Desktop/UIUC/Research/Metis/model/device_group.py", line 78, in get_intra_stage_compute_performance
    execution_costs = self._get_hetero_device_group_execution_time(device_types, intra_strategy, hetero_bs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jimmy/Desktop/UIUC/Research/Metis/model/device_group.py", line 50, in _get_hetero_device_group_execution_time
    comb_h_mbs = [2 ** i for i in range(int(math.log2(h_mbs)), -1, -1) if h_mbs & 2 ** i]
                                            ^^^^^^^^^^^^^^^^
ValueError: math domain error
```

### Possible fixes
-  Similar to cost_estimator.py, add the small snippet to load_balancer.py and device_group.py
```
if h_mbs == 0:
    continue
```
-  Modify the partition_data function in load_balancer.py to initialize a batch size of at least 1 for each GPU
- when constructing comb_h_mbs, append value of 0 if h_mbs ==0. In other words, do the following replacemnent in  load_balancer.py and device_group.py
```
# Replace: comb_h_mbs = [2 ** i for i in range(int(math.log2(h_mbs)), -1, -1) if h_mbs & 2 ** i]
comb_h_mbs = [2 ** i for i in range(int(math.log2(h_mbs)) if h_mbs != 0 else 0, -1, -1) if h_mbs & 2 ** i]
```
- Each of these three fixes results in different values using the given reproduction steps, which is why I decided to write a issue request so the repo authors have better insights into how to fix the issue

### Notes
- to verify that this only occurs in heterogenous clusters, you can change the v100 script's factor from 3.5 to 1. The error no longer occurs since the load balancer would assign batch sizes equally across devices.

### Necessary files for reproduction
clusterfile.json
```
{
    "0.0.0.1": {
            "instance_type": "V100",
            "inter_bandwidth": 10,
            "intra_bandwidth": 50,
            "memory": 16
        },
    "0.0.0.2": {
            "instance_type": "P100",
            "inter_bandwidth": 10,
            "intra_bandwidth": 50,
            "memory": 15
        },
    "0.0.0.3": {
           "instance_type": "T4",
           "inter_bandwidth": 10,
           "intra_bandwidth": 50,
           "memory": 15
        },
    "0.0.0.4": {
           "instance_type": "A100",
           "inter_bandwidth": 10,
           "intra_bandwidth": 46,
           "memory": 80
   }
}
```

hostfile
```
0.0.0.1 slots=4
0.0.0.1 slots=4
0.0.0.1 slots=4
0.0.0.1 slots=4
0.0.0.4 slots=4
0.0.0.4 slots=4
0.0.0.4 slots=4
0.0.0.4 slots=4
```

gen_synth_data.py
```
import json
import os
import re

def create_v100_files(profile_dir):
    # Define the scaling factor for execution time
    factor = 3.5
    
    # Iterate over all files in the profile directory
    for filename in os.listdir(profile_dir):
        # Match files with the pattern "DeviceType.A100_tpX_bsY.json"
        if re.match(r'DeviceType\.A100_tp\d+_bs\d+\.json', filename):
            # Construct full file path
            a100_filepath = os.path.join(profile_dir, filename)
            
            # Load A100 JSON data
            with open(a100_filepath, 'r') as file:
                a100_data = json.load(file)
            
            # Prepare V100 data by scaling execution time fields
            v100_data = a100_data.copy()
            v100_data['execution_time']['total_time_ms'] *= factor
            v100_data['execution_time']['forward_backward_time_ms'] *= factor
            v100_data['execution_time']['batch_generator_time_ms'] *= factor
            v100_data['execution_time']['layernorm_grads_all_reduce_time_ms'] *= factor
            v100_data['execution_time']['embedding_grads_all_reduce_time_ms'] *= factor
            v100_data['execution_time']['optimizer_time_ms'] *= factor
            v100_data['execution_time']['layer_compute_total_ms'] = [
                time * factor for time in v100_data['execution_time']['layer_compute_total_ms']
            ]
            
            # Generate the V100 filename and save the modified data
            v100_filename = filename.replace("A100", "V100")
            v100_filepath = os.path.join(profile_dir, v100_filename)
            
            with open(v100_filepath, 'w') as outfile:
                json.dump(v100_data, outfile, indent=2)
            
            print(f"Generated: {v100_filepath}")

# Usage example
create_v100_files("./profile")
```

**Comment by mgong-kang** [comment]
Thank you for your interest in this project. The issue mentioned is a part that was missed and should be handled in the code. All three methods you suggested seem suitable for resolving this issue. In terms of performance, methods 1 and 3, which skip cases where h_mbs is 0, are more appropriate than assigning a minimal batch size. For code simplicity, method 3 seems the most fitting. 

```python 
# Replace: comb_h_mbs = [2 ** i for i in range(int(math.log2(h_mbs)), -1, -1) if h_mbs & 2 ** i]
comb_h_mbs = [2 ** i for i in range(int(math.log2(h_mbs)) if h_mbs != 0 else 0, -1, -1) if h_mbs & 2 ** i]
```

However, applying method 3 would result in an empty list being passed to _execution_costs_, which could case issues in measuring _stage_performance_. Therefore, additional handling is needed in this part. 

If you submit a PR, I will incorporate it. Alternatively, if you prefer, I can update the code directly.

**Comment by Jiminator** [comment]
Since this codebase is relatively new and I am still figuring out the components (as evidenced by the issue with exeuction_costs), could you update the code directly? As I become more familiar with the codebase, I will be more confident in submitting PRs to the codebase If I discover any issues in the future.

Thank you for your timely response!

**Comment by mgong-kang** [comment]
The issue has been resolved in the PR(https://github.com/SamsungLabs/Metis/pull/8). Thank you for your review.

**Comment by Jiminator** [comment]
I believe the issue is not entirely fixed since the exact change needs to be made to load_balancer.py to avoid the math domain error. I can submit a PR for this fix.

On another note, I believe there is another bug where if we turn one of the a100s into a v100, the profiler tries to look for profile data with bs = 9, even though we pass in MAX_PROFILED_BATCH_SIZE=4. I do not believe this is intended behavior, but I am not sure what the best way to fix it is if it is unintended.

**Comment by mgong-kang** [comment]
I'll also look into debugging the issue you mentioned and get back to you. Thank you.
